name: VoteShop
main: com.DeStilleGast.Minecraft.HappyMine.VoteShop.ShopCore
version: 0.1.1
author: DeStilleGast
api-version: 1.13

depend:
  - Votifier

softdepend:
  - DSGUtils

commands:
  voteshop:
    description: Spendeer je vote points voor speciale perks
    usage: /voteshop